name: Requestor

on:
  push:
    branches: 
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: golang:alpine
    steps:
    - uses: actions/checkout@v2
      
    - name: go version
      run: go version

    - name: Hello
      run: echo hello
