name: Requestor

on:
  push:
    branches: 
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: 
      image: golang:alpine
    steps:
    - uses: actions/checkout@v2
      
    - name: go tests
      run: go test ./...
