name: Requestor

on:
  push:
    branches: 
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: 
      image: golang
    steps:
    - uses: actions/checkout@v2

    - name: go version
      run: go version

    - name: Install Dependencies
      run: apt update && apt install musl-dev libffi-dev gcc git libc-dev curl -y

    - name: go test
      run: mkdir cover && go test -coverprofile=cover/cover.out

    - name: Create Coverage Artifact
      run: go tool cover -html=cover/cover.out -o cover/coverage.html

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Coverage
        path: cover/coverage.html

    - name: Upload to Codecov
      run: CODECOV_TOKEN={{ secrets.CODECOV_TOKEN }} bash <(curl -s https://codecov.io/bash)
